### ISSUE TITLE
Горизонтальная прокрутка на главной странице

### ISSUE THREAD

**Issue by X1Z53** [OlegShchavelev/ALTGnomeWiki#594]
На [главной странице](alt-gnome.wiki) появляется горизонтальная прокрутка, однако сама страница на подобное не рассчитана

Данный баг проявляется только тогда, когда переход осуществлён сразу на страницу, а не через меню навигации или иными способами

https://github.com/user-attachments/assets/ac47ecb7-f94c-4c3e-8c54-9d5d80de6d93

**Comment by Ampernic** [comment]
Если возможно - проверь на данный момент проявление ошибки.
И опиши подробнее этот момент, у меня почему-то не проявляется
:(

**Comment by OlegShchavelev** [comment]
У меня воспроизводиться (Яндекс Браузер):
![image](https://github.com/user-attachments/assets/769c4e67-8071-4554-92dc-9d0917d82993)

**Comment by Ampernic** [comment]
Исправлено в 624b9776a1e3d0b6f7e6052539fcb69cde3c6d22

В каком-то из обновлений vitepress были изменены [стили VPTeamPage и VPSponsors](https://github.com/vuejs/vitepress/blob/3eb4374af286362d7f4257b288fd2d5b9173dcba/src/client/theme-default/components/VPHomeContent.vue#L40) на:
```css
.vp-doc :deep(.VPHomeSponsors),
.vp-doc :deep(.VPTeamPage) {
  margin-left: var(--vp-offset, calc(50% - 50vw));
  margin-right: var(--vp-offset, calc(50% - 50vw));
}
```
Что давало неверный подсчет ширины в нашей реализации.
